### ISSUE TITLE
Train Problems

### ISSUE THREAD

**Issue by fernandolimati** [ColeMurray/medium-facenet-tutorial#5]
I got this error message from your train_classfier.py code. Any help?

`2017-10-16 21:12:52.553185: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-16 21:12:52.553276: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
INFO:root:Model filename: /medium-facenet-tutorial/etc/20170511-185253/20170511-185253.pb
Traceback (most recent call last):
  File "/medium-facenet-tutorial/train_classifier.py", line 207, in <module>
    min_images_per_labels=args.min_images_per_class, split_ratio=args.split_ratio, is_train=args.is_train)
  File "/medium-facenet-tutorial/train_classifier.py", line 66, in main
    logger.info('Created {} embeddings'.format(len(emb_array)))
TypeError: object of type 'NoneType' has no len()
`

**Comment by fernandolimati** [comment]
i skip one step, my bad. sorry!
